import { useState } from 'react';
import { ArrowRight, CarFront, CheckCircle2, ChevronRight, Clock3, Leaf, MapPin, Menu, ShieldCheck, Sparkles, UserRound, X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion';
import KayanMap from '@/components/KayanMap';
import BookingPanel, { type ActiveRide, type Destination, type Ride } from '@/components/BookingPanel';
import TripPanel from '@/components/TripPanel';
import { toast } from 'sonner';
import { Link } from 'react-router-dom';
import ThemeSelect from '@/components/ThemeSelect';
import KayanLogo from '@/components/KayanLogo';

type View = 'book' | 'activity';
type Modal = 'welcome' | 'support' | 'account' | null;
const Brand = () => <div className="flex items-center gap-2.5"><img src="/assets/kayan-eagle.png" alt="KAYAN eagle" className="h-11 w-11 rounded-xl object-cover"/><div><span className="display-font text-2xl font-extrabold tracking-[.2em] text-[#fff3df]">KAYAN</span><span className="mt-0.5 block text-[8px] font-semibold uppercase tracking-[.34em] text-[#e49656]">A better way to ride</span></div></div>;

export default function Index() {
  const [view, setView] = useState<View>('book');
  const [modal, setModal] = useState<Modal>(null);
  const [mobileMenu, setMobileMenu] = useState(false);
  const [destination, setDestination] = useState<Destination | null>(null);
  const [activeRide, setActiveRide] = useState<ActiveRide | null>(null);
  const [rides, setRides] = useState<Ride[]>([]);
  const [selectedRide, setSelectedRide] = useState<Ride | null>(null);
  const [rating, setRating] = useState(0);
  const [tripStage, setTripStage] = useState(0);
  const navigate = (v: View) => { setView(v); setMobileMenu(false); };
  const finish = (cancelled: boolean) => {
    if (!activeRide) return;
    setRides(previous => [{ ...activeRide, date: new Date().toLocaleString(), status: cancelled ? 'Cancelled' : 'Completed' }, ...previous]);
    setActiveRide(null); setDestination(null); setView('activity');
    toast.success(cancelled ? 'Demo ride cancelled. No charge applied.' : 'Demo ride completed. No payment collected.');
  };
  const nav = <>
    <div className="mb-8 px-3"><Brand/></div>
    <p className="mb-3 px-4 text-[9px] font-semibold uppercase tracking-[.2em] text-[#9ab3a4]">Your everyday journey</p>
    <button onClick={() => navigate('book')} className={`nav-item ${view === 'book' ? 'bg-[#20483a] text-[#fff3df]' : 'text-[#b8cbbd] hover:bg-card/5'}`}><CarFront size={19} className={view === 'book' ? 'text-[#e99655]' : ''}/> {activeRide ? 'Your current ride' : 'Book a ride'}{view === 'book' && <span className="ml-auto h-1.5 w-1.5 rounded-full bg-primary"/>}</button>
    <button onClick={() => navigate('activity')} className={`nav-item mt-1 ${view === 'activity' ? 'bg-[#20483a] text-[#fff3df]' : 'text-[#b8cbbd] hover:bg-card/5'}`}><Clock3 size={19}/> Your activity {rides.length > 0 && <span className="ml-auto text-xs">{rides.length}</span>}</button>
    <button onClick={() => { setModal('support'); setMobileMenu(false); }} className="nav-item mt-1 text-[#b8cbbd] hover:bg-card/5"><ShieldCheck size={19}/> Safety & support</button>
    <Link to="/website" className="nav-item mt-1 text-[#b8cbbd] hover:bg-white/5"><UserRound size={19}/> Join KAYAN website</Link>
    <Link to="/driver" className="nav-item mt-1 text-[#e99655] hover:bg-white/5"><CarFront size={19}/> KAYAN Driver demo</Link>
    <Link to="/projects" className="nav-item mt-1 text-[#b8cbbd] hover:bg-white/5"><ArrowRight size={19}/> Download APK projects</Link>
    <div className="mt-auto pt-16"><div className="mx-2 rounded-2xl border border-[#42604b] bg-[#123a2c] p-4"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#d87932]/15"><Leaf size={19} className="text-[#e99655]"/></span><p className="mt-3 text-sm font-semibold text-[#fff3df]">Rooted in Zambia.</p><p className="mt-2 text-xs leading-relaxed text-[#b8cbbd]">Better journeys for our people. Better opportunities for our drivers.</p><button onClick={() => { setModal('welcome'); setMobileMenu(false); }} className="mt-4 flex items-center gap-2 text-xs font-bold text-[#e99655]">Meet KAYAN <ArrowRight size={14}/></button></div><div className="mx-4 mt-6 flex items-center gap-2 border-t border-white/10 pt-5 text-[10px] text-[#b8cbbd]"><MapPin size={13} className="text-[#e99655]"/> Lusaka, Zambia <span className="ml-auto rounded-full bg-card/10 px-2 py-1 text-[8px]">PREVIEW</span></div></div>
  </>;
  return <div className="min-h-screen lg:flex">
    <aside className="sticky top-0 hidden h-screen w-[226px] shrink-0 flex-col bg-[var(--forest)] px-4 py-8 lg:flex">{nav}</aside>
    <div className="min-w-0 flex-1">
      <header className="flex h-[78px] items-center justify-between border-b bg-card/70 px-5 lg:px-9"><div className="flex items-center gap-3"><button onClick={() => setMobileMenu(true)} className="rounded-lg p-1.5 lg:hidden" aria-label="Open navigation"><Menu size={22}/></button><KayanLogo className="h-9 w-9 lg:hidden"/><span className="display-font text-sm font-extrabold tracking-[.15em] lg:hidden">KAYAN</span><div className="hidden items-center gap-2 text-xs text-muted-foreground sm:flex"><MapPin size={15} className="text-primary"/> Lusaka <ChevronRight size={12}/><span className="font-semibold text-foreground">{view === 'book' ? 'Book a ride' : 'Your activity'}</span></div></div><div className="flex items-center gap-2 sm:gap-4"><ThemeSelect/><span className="hidden sm:inline-block rounded-full border border-[#dbcab5] bg-accent px-2.5 py-1.5 text-[9px] font-bold uppercase tracking-wider text-foreground">Passenger preview</span><button onClick={() => setModal('account')} aria-label="Open passenger account" className="flex h-10 w-10 items-center justify-center rounded-full border border-border bg-secondary"><UserRound size={19}/></button></div></header>
      <main className="mx-auto max-w-[1500px] p-4 sm:p-6 lg:px-9 lg:py-7">
        <div className="mb-6 flex items-end justify-between"><div><p className="mb-2 text-[10px] font-semibold uppercase tracking-[.2em] text-muted-foreground">YOUR CITY. YOUR JOURNEY.</p><h1 className="text-2xl font-extrabold tracking-tight sm:text-[30px]">{view === 'book' ? <>Good journeys start with <span className="text-primary">KAYAN.</span></> : 'Every journey, in one place.'}</h1><p className="mt-2 text-xs text-muted-foreground">{view === 'book' ? 'Wherever life takes you, let’s get there better.' : 'Your demo rides from this browser session.'}</p></div><div className="hidden items-center gap-2 pb-1 text-[10px] font-semibold text-muted-foreground xl:flex"><ShieldCheck size={16} className="text-primary"/> Professional by design</div></div>
        {view === 'book' ? <>
          <div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_365px] 2xl:grid-cols-[minmax(0,1fr)_400px]">
            <div className="min-w-0"><KayanMap stage={activeRide ? tripStage : null} hasRoute={!!destination || !!activeRide} destination={(activeRide?.destination || destination)?.name || ''}/></div>
            <section className="rounded-2xl border border-border bg-card p-5 sm:p-6">{activeRide ? <TripPanel key={activeRide.id} ride={activeRide} stage={tripStage} onStage={setTripStage} onFinish={finish} onSupport={() => setModal('support')}/> : <BookingPanel destination={destination} onDestination={setDestination} onBook={ride => { setTripStage(0); setActiveRide(ride); }}/>}</section>
          </div>
          <div className="mt-5 grid gap-4 md:grid-cols-[1fr_1fr_1fr]">
            <div className="flex items-center gap-3 rounded-xl border border-border bg-card/70 p-4"><div className="rounded-xl bg-secondary p-2.5"><Sparkles size={20}/></div><div><h3 className="text-xs font-bold">A higher standard</h3><p className="mt-1 text-[10px] text-muted-foreground">Clean cars. A comfortable journey.</p></div></div>
            <div className="flex items-center gap-3 rounded-xl border border-border bg-card/70 p-4"><div className="rounded-xl bg-accent p-2.5 text-primary"><ShieldCheck size={20}/></div><div><h3 className="text-xs font-bold">You come first</h3><p className="mt-1 text-[10px] text-muted-foreground">Safety at the heart of the experience.</p></div></div>
            <button onClick={() => setModal('welcome')} className="group relative flex min-h-[80px] items-center overflow-hidden rounded-xl bg-[#173f30] p-4 text-left"><div className="relative z-10"><h3 className="text-xs font-bold text-[#fff3df]">Made for Zambia</h3><p className="mt-1 flex items-center gap-2 text-[10px] text-[#e99655]">Discover the KAYAN difference <ArrowRight size={12}/></p></div><img src="/assets/kayan-driver.png" alt="Illustrative professional KAYAN service" className="absolute right-0 top-0 h-full w-[32%] object-cover object-center transition-transform group-hover:scale-105"/></button>
          </div>
        </> : <section className="min-h-[600px] rounded-2xl border bg-card p-6 sm:p-8"><div className="flex items-center justify-between"><h2 className="text-lg font-bold">Your activity</h2><span className="rounded-full bg-secondary px-3 py-1 text-[10px] text-muted-foreground">Session only</span></div>{rides.length === 0 ? <div className="flex flex-col items-center py-16 text-center"><img src="/assets/ride-empty.png" alt="Taxi and destination illustration" className="mb-6 h-40 w-40 rounded-3xl"/><h3 className="text-xl font-bold">Your first journey awaits.</h3><p className="mb-6 mt-2 max-w-sm text-sm text-muted-foreground">Take the passenger experience for a spin. Completed and cancelled demo rides will appear here.</p><Button className="kayan-action" onClick={() => navigate('book')}>Explore a ride <ArrowRight size={16} className="ml-2"/></Button></div> : <div className="mt-6 space-y-3">{rides.map(ride => <button key={ride.id} onClick={() => { setSelectedRide(ride); setRating(0); }} className="flex w-full items-center gap-4 rounded-xl border p-4 text-left hover:bg-secondary"><span className="rounded-xl bg-secondary p-3"><CarFront size={24}/></span><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">{ride.destination.name}</p><p className="mt-1 text-[11px] text-muted-foreground">{ride.date} · {ride.category}</p><span className={`mt-2 inline-block rounded-full px-2 py-1 text-[9px] font-semibold ${ride.status === 'Completed' ? 'bg-[#e8f2e7] text-[#305f39]' : 'bg-[#fbece8] text-[#a34533]'}`}>{ride.status} · Demo</span></div><div className="text-right"><p className="text-sm font-bold">K{ride.price}</p><p className="mt-1 text-[10px] text-muted-foreground">Not charged</p></div><ChevronRight size={16}/></button>)}</div>}</section>}
        <footer className="mt-6 flex flex-wrap items-center justify-between gap-2 text-[9px] text-muted-foreground"><span>© {new Date().getFullYear()} KAYAN · Built around you.</span><span>Prototype · No live dispatch, payments, or emergency monitoring</span></footer>
      </main>
    </div>
    {mobileMenu && <div className="fixed inset-0 z-50 bg-[#062d24]/60 lg:hidden" onClick={() => setMobileMenu(false)}><aside className="flex h-full w-[280px] flex-col overflow-y-auto bg-[var(--forest)] px-4 py-8" onClick={e => e.stopPropagation()}><button aria-label="Close navigation" onClick={() => setMobileMenu(false)} className="absolute left-[245px] top-4 text-[#fff3df]"><X size={20}/></button>{nav}</aside></div>}
    <Dialog open={modal !== null} onOpenChange={open => { if (!open) setModal(null); }}><DialogContent className={`max-h-[90vh] overflow-y-auto rounded-3xl ${modal === 'welcome' ? 'max-w-2xl p-0' : 'max-w-lg p-6 sm:p-8'}`}>
      {modal === 'welcome' && <div className="grid sm:grid-cols-2"><img src="/assets/kayan-driver.png" alt="Illustrative clean taxi and professional driver in Lusaka" className="h-56 w-full object-cover sm:h-full"/><div className="p-7"><DialogHeader><p className="mb-3 text-[10px] font-bold uppercase tracking-[.2em] text-primary">Introducing KAYAN</p><DialogTitle className="text-3xl font-extrabold leading-tight">A better ride.<br/>A brighter journey.</DialogTitle><DialogDescription className="pt-3 leading-relaxed">Our vision is simple: raise the standard of everyday taxi travel in Zambia, for passengers and drivers alike.</DialogDescription></DialogHeader><div className="my-6 space-y-3">{['Clean, well-maintained vehicles', 'Courteous, professional drivers', 'Clear fares before you ride'].map(t => <p key={t} className="flex items-center gap-2 text-xs font-semibold"><CheckCircle2 size={16} className="text-primary"/>{t}</p>)}</div><Button onClick={() => { setModal(null); navigate('book'); }} className="kayan-action w-full">Explore the passenger app <ArrowRight size={16} className="ml-2"/></Button><p className="mt-3 text-[10px] leading-relaxed text-muted-foreground">Illustrative brand imagery. This preview does not represent an operational fleet.</p></div></div>}
      {modal === 'account' && <><DialogHeader><span className="mb-3 flex h-12 w-12 items-center justify-center rounded-2xl bg-secondary"><UserRound size={24}/></span><DialogTitle className="text-2xl">Welcome, passenger.</DialogTitle><DialogDescription>You’re exploring KAYAN as a guest. Account sign-in is not connected in this prototype.</DialogDescription></DialogHeader><div className="rounded-xl bg-secondary p-4 text-sm leading-relaxed">Your demo rides and saved home are kept only while this page remains open. Reloading clears this session. No personal account or payment details are collected.</div><Link to="/website" className="kayan-action flex items-center justify-center">Explore registration demo</Link><Button variant="outline" className="h-11 rounded-xl" onClick={() => setModal(null)}>Continue as guest</Button></>}
      {modal === 'support' && <><DialogHeader><span className="mb-3 flex h-12 w-12 items-center justify-center rounded-2xl bg-accent text-primary"><ShieldCheck size={24}/></span><DialogTitle className="text-2xl">Safety & support</DialogTitle><DialogDescription>Know what to expect before you ride.</DialogDescription></DialogHeader><div className="rounded-xl border border-[#e8c7b3] bg-accent p-4"><h3 className="text-xs font-bold">This is not an emergency service.</h3><p className="mt-2 text-xs leading-relaxed text-muted-foreground">No live support team or safety monitoring is connected. In immediate danger, contact local emergency services directly. Do not rely on this prototype for help.</p></div><Accordion type="single" collapsible className="w-full"><AccordionItem value="safety"><AccordionTrigger className="text-sm">Before getting into a taxi</AccordionTrigger><AccordionContent className="text-xs leading-relaxed text-muted-foreground">Confirm the driver, vehicle, and plate match your booking. Share trip details with someone you trust. Only give your pickup code to the matched driver and wear your seatbelt.</AccordionContent></AccordionItem><AccordionItem value="fares"><AccordionTrigger className="text-sm">How do demo fares work?</AccordionTrigger><AccordionContent className="text-xs leading-relaxed text-muted-foreground">Prices and travel times are illustrative, not live quotations. Comfort adds K30 in this preview. Cash and mobile money are preferences only; no money is collected.</AccordionContent></AccordionItem><AccordionItem value="contact"><AccordionTrigger className="text-sm">Contacting KAYAN</AccordionTrigger><AccordionContent className="text-xs leading-relaxed text-muted-foreground">Official KAYAN support details have not been supplied yet. No message can be sent from this prototype. A staffed support channel must be configured before real rides launch.</AccordionContent></AccordionItem><AccordionItem value="privacy"><AccordionTrigger className="text-sm">Your privacy in this preview</AccordionTrigger><AccordionContent className="text-xs leading-relaxed text-muted-foreground">Device location is requested only when you enable it on the map. Tracking stops when the app is hidden or you stop it. Location is not saved or sent to KAYAN. OpenStreetMap tile requests expose the viewed area and IP to its provider. Ride data stays in this page’s memory and clears on refresh. Sharing copies demo details to your clipboard; it does not create a live tracking link.</AccordionContent></AccordionItem></Accordion><Button variant="outline" className="h-11 rounded-xl" onClick={() => setModal(null)}>Back to the app</Button></>}
    </DialogContent></Dialog>
    <Dialog open={!!selectedRide} onOpenChange={open => { if (!open) setSelectedRide(null); }}><DialogContent className="max-w-md rounded-3xl p-7">{selectedRide && <><DialogHeader><DialogTitle className="text-2xl">Journey details</DialogTitle><DialogDescription>{selectedRide.id} · {selectedRide.status}</DialogDescription></DialogHeader><div className="space-y-4 rounded-xl bg-secondary p-4"><div><p className="text-[10px] text-muted-foreground">From</p><p className="text-sm font-semibold">{selectedRide.pickup}</p></div><div><p className="text-[10px] text-muted-foreground">To</p><p className="text-sm font-semibold">{selectedRide.destination.name}</p></div><div className="flex justify-between border-t pt-3"><span className="text-xs">{selectedRide.payment} · Not charged</span><span className="font-bold">K{selectedRide.price}</span></div></div>{selectedRide.status === 'Completed' && <div><p className="mb-3 text-sm font-semibold">How was the demo experience?</p><div className="flex gap-2">{[1,2,3,4,5].map(n => <button key={n} onClick={() => setRating(n)} aria-label={`Rate ${n} out of 5`} aria-pressed={rating === n} className={`h-10 w-10 rounded-xl border text-sm font-bold ${rating >= n ? 'border-primary bg-primary text-white' : 'bg-secondary'}`}>{n}</button>)}</div><p className="mt-2 text-[10px] text-muted-foreground">Preview feedback only · not sent to a driver.</p><Button disabled={!rating} className="kayan-action mt-4 w-full" onClick={() => { toast.success('Thanks for trying the rating interaction. No feedback was submitted.'); setSelectedRide(null); }}>Finish feedback preview</Button></div>}</>}</DialogContent></Dialog>
  </div>;
}
