import { useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft, ArrowRight, CarFront, CheckCircle2, Download, FileCheck2, ShieldCheck, Sparkles, UserRound } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import ThemeSelect from '@/components/ThemeSelect';

export default function Website() {
  const [tab, setTab] = useState('passenger');
  const [done, setDone] = useState<string | null>(null);
  const [files, setFiles] = useState<Record<string, string>>({});
  const [fileError, setFileError] = useState('');
  const field = (id: string, title: string, type = 'text', placeholder = '', extra: Record<string, string | number> = {}) => <div className="space-y-2"><Label htmlFor={id} className="text-xs">{title}</Label><Input id={id} name={id} type={type} required maxLength={120} placeholder={placeholder} className="h-11 rounded-xl bg-background/60" {...extra}/></div>;
  const submit = (e: React.FormEvent<HTMLFormElement>, kind: string) => { e.preventDefault(); e.currentTarget.reset(); setFiles({}); setDone(kind); };
  return <div className="min-h-screen bg-background">
    <header className="border-b bg-card"><div className="mx-auto flex max-w-6xl flex-wrap items-center justify-between gap-3 px-5 py-4 sm:px-8"><Link to="/" className="flex items-center gap-2.5"><img src="/assets/kayan-eagle.png" alt="KAYAN eagle" className="h-10 w-10 rounded-xl"/><span className="display-font text-xl font-extrabold tracking-[.2em]">KAYAN</span></Link><div className="flex items-center gap-3"><ThemeSelect/><Link to="/" className="flex items-center gap-1.5 text-xs font-semibold"><ArrowLeft size={14}/> Passenger app</Link></div></div></header>
    <main className="mx-auto max-w-6xl px-5 py-8 sm:px-8 sm:py-12">
      <div className="mb-8 flex flex-wrap items-center justify-between gap-3 rounded-xl border bg-accent/50 p-3.5"><p className="text-xs leading-relaxed"><strong>Website demo.</strong> No accounts are created and no applications or documents are submitted. Use fictional details.</p><a href="/kayan-demo.html" download className="flex shrink-0 items-center gap-2 rounded-lg border bg-card px-3 py-2 text-xs font-semibold"><Download size={15}/> Download HTML demo</a></div>
      <div className="grid items-start gap-8 lg:grid-cols-[1fr_1.05fr] lg:gap-14">
        <section><p className="mb-4 text-[10px] font-bold uppercase tracking-[.25em] text-primary">Zambian roots. Higher standards.</p><h1 className="text-4xl font-extrabold leading-[1.15] tracking-tight sm:text-5xl">Good journeys.<br/><span className="text-primary">Great possibilities.</span></h1><p className="mt-5 max-w-md text-sm leading-relaxed text-muted-foreground">Whether you’re heading across town or ready to get behind the wheel, there’s a place for you at KAYAN.</p><div className="relative mt-7 overflow-hidden rounded-3xl"><img src="/assets/kayan-driver.png" alt="Illustrative professional driver and clean taxi in Lusaka" className="h-[320px] w-full object-cover object-[center_65%]"/><div className="absolute bottom-4 left-4 right-4 rounded-2xl bg-[var(--forest)] p-4 text-[var(--cream)]"><p className="text-sm font-bold">A better way to ride. Together.</p><p className="mt-1 text-[10px] text-[#b8cbbd]">Brand illustration · not an operational fleet</p></div></div><div className="mt-5 grid grid-cols-3 gap-3">{[[Sparkles, 'Clean cars'], [ShieldCheck, 'Professional service'], [CarFront, 'Built for Zambia']].map(([Icon, text]) => { const I = Icon as typeof Sparkles; return <div key={String(text)} className="rounded-xl border bg-card p-3"><I size={18} className="mb-2 text-primary"/><p className="text-[10px] font-semibold">{String(text)}</p></div>; })}</div></section>
        <section className="rounded-3xl border bg-card p-5 shadow-sm sm:p-7">
          <Tabs value={tab} onValueChange={v => { setTab(v); setDone(null); setFileError(''); setFiles({}); }}><TabsList className="mb-7 grid h-12 w-full grid-cols-2 rounded-xl bg-secondary p-1"><TabsTrigger value="passenger" className="h-10 gap-2 rounded-lg text-xs data-[state=active]:bg-card"><UserRound size={15}/> Join as passenger</TabsTrigger><TabsTrigger value="driver" className="h-10 gap-2 rounded-lg text-xs data-[state=active]:bg-card"><CarFront size={15}/> Become a driver</TabsTrigger></TabsList>
            {done ? <div role="status" className="py-12 text-center"><CheckCircle2 className="mx-auto mb-4 text-primary" size={44}/><h2 className="text-2xl font-bold">Demo {done} complete</h2><p className="my-4 text-sm leading-relaxed text-muted-foreground">Your form passed the demo validation. Nothing was submitted, stored, or approved. No account has been created.</p><Button className="kayan-action" onClick={() => setDone(null)}>Try again</Button></div> : <>
              <TabsContent value="passenger"><h2 className="text-2xl font-extrabold">Your next journey starts here.</h2><p className="mb-6 mt-2 text-xs leading-relaxed text-muted-foreground">Preview passenger registration. Please use fictional information, not your real password.</p><form className="space-y-4" onSubmit={e => submit(e, 'registration')}>{field('passenger-name', 'Full name', 'text', 'Example Passenger')}{field('passenger-email', 'Email address', 'email', 'passenger@example.com')}{field('passenger-phone', 'Phone number', 'tel', '+260 97 000 0000', { pattern: '\\+?[0-9 ()-]{9,20}', maxLength: 20 })}{field('demo-password', 'Demo password (8+ characters)', 'password', 'Use a fictional password', { minLength: 8, autoComplete: 'new-password' })}<label className="flex items-start gap-2 text-xs leading-relaxed text-muted-foreground"><input type="checkbox" required className="mt-0.5 h-4 w-4 accent-[#d87932]"/> I understand this is a local demonstration and no real account will be created.</label><Button type="submit" className="kayan-action w-full justify-between">Preview registration <ArrowRight size={16}/></Button></form></TabsContent>
              <TabsContent value="driver"><h2 className="text-2xl font-extrabold">Drive with purpose.</h2><p className="mb-5 mt-2 text-xs leading-relaxed text-muted-foreground">Preview the driver application process. Subscription pricing and benefits are not finalized; no payment or approval happens here.</p><form className="space-y-4" onSubmit={e => submit(e, 'application')}><div className="grid gap-4 sm:grid-cols-2">{field('driver-name', 'Full name', 'text', 'Example Driver')}{field('driver-phone', 'Phone number', 'tel', '+260 97 000 0000', { pattern: '\\+?[0-9 ()-]{9,20}', maxLength: 20 })}</div>{field('driver-email', 'Email address', 'email', 'driver@example.com')}<div className="grid gap-4 sm:grid-cols-2">{field('vehicle-make', 'Vehicle make / model', 'text', 'Toyota Corolla')}{field('vehicle-year', 'Vehicle year', 'number', '2020', { min: 1980, max: new Date().getFullYear() + 1 })}</div><div className="grid gap-4 sm:grid-cols-2">{field('vehicle-plate', 'Vehicle registration', 'text', 'DEMO 001')}{field('city', 'Operating city', 'text', 'Lusaka')}</div>
                <fieldset className="rounded-2xl border bg-background/50 p-4"><legend className="px-1 text-xs font-bold">Document-selection demo</legend><p className="mb-3 text-[10px] leading-relaxed text-muted-foreground">Optional. Use sample files only. PDF, JPG or PNG, maximum 5 MB each. Files are not read, uploaded, or stored; only their names are displayed.</p>{['Driving licence', 'Vehicle registration document', 'Vehicle photo'].map((name, i) => <div key={name} className="mb-3 last:mb-0"><Label htmlFor={`doc-${i}`} className="mb-2 block text-[11px]">{name}</Label><input id={`doc-${i}`} type="file" accept=".pdf,.jpg,.jpeg,.png" className="block w-full min-w-0 text-[10px] text-muted-foreground file:mr-2 file:rounded-lg file:border-0 file:bg-secondary file:px-3 file:py-2 file:font-semibold file:text-foreground" onChange={e => { const f = e.target.files?.[0]; if (!f) { setFiles(previous => ({ ...previous, [name]: '' })); return; } if (f.size > 5 * 1024 * 1024 || !/\.(pdf|jpe?g|png)$/i.test(f.name)) { e.target.value = ''; setFiles(previous => ({ ...previous, [name]: '' })); setFileError('Choose a PDF, JPG or PNG no larger than 5 MB.'); return; } setFileError(''); setFiles(previous => ({ ...previous, [name]: f.name })); }}/>{files[name] && <p className="mt-1 flex items-center gap-1 break-all text-[10px] text-muted-foreground"><FileCheck2 size={12}/>{files[name]} · selected locally</p>}</div>)}{fileError && <p role="alert" className="mt-2 text-xs text-destructive">{fileError}</p>}</fieldset>
                <label className="flex items-start gap-2 text-xs leading-relaxed text-muted-foreground"><input type="checkbox" required className="mt-0.5 h-4 w-4 accent-[#d87932]"/> I understand this is a demo application, not a driver approval or agreement.</label><Button type="submit" className="kayan-action w-full justify-between">Preview application <ArrowRight size={16}/></Button></form></TabsContent>
            </>}
          </Tabs><div className="mt-6 border-t pt-4 text-[10px] leading-relaxed text-muted-foreground">Demo information remains in this page only. Before launch, KAYAN needs secure accounts, private document storage, eligibility rules, and authorized driver review.</div>
        </section>
      </div>
      <footer className="mt-12 flex flex-wrap justify-between gap-3 border-t pt-5 text-[10px] text-muted-foreground"><span>KAYAN · A better way to ride.</span><span>Responsive web demo · no native Android/iOS features</span><Link to="/" className="font-semibold text-primary">Return to passenger app →</Link></footer>
    </main>
  </div>;
}
