import { useState } from 'react';
import { ArrowRight, CheckCircle2, MapPin, MessageCircle, Phone, Send, UserRound } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';

export type DemoRequest = { id: string; passenger: string; pickup: string; destination: string; fare: number; distance: string };
export const tripStages = ['Heading to pickup', 'At pickup', 'Trip in progress', 'Drop-off reached'];
export default function DriverTrip({ request, stage, onStage, onFinish }: { request: DemoRequest; stage: number; onStage: (stage: number) => void; onFinish: (cancelled: boolean) => void }) {
  const [modal, setModal] = useState<'chat' | 'call' | null>(null);
  const [calling, setCalling] = useState(false);
  const [draft, setDraft] = useState('');
  const [messages, setMessages] = useState<{ author: string; text: string }[]>([{ author: 'Passenger · scripted', text: 'Hi! I’ll be waiting by the main entrance.' }]);
  return <section className="rounded-3xl border bg-card p-6">
    <div className="flex items-center justify-between"><span className="text-[10px] font-bold uppercase tracking-widest text-primary">Active demo trip</span><span className="rounded-full bg-secondary px-3 py-1 text-[10px]">{request.id}</span></div>
    <h2 className="mt-3 text-2xl font-extrabold">{tripStages[stage]}</h2><p className="mt-2 text-xs leading-5 text-muted-foreground">Advance stages manually. No GPS, real ETA, or live passenger.</p>
    <ol className="my-6 space-y-4">{tripStages.map((title, i) => <li key={title} className={`flex items-center gap-3 text-xs ${i > stage ? 'text-muted-foreground' : 'font-semibold'}`}><span className={`flex h-7 w-7 items-center justify-center rounded-full ${i <= stage ? 'bg-primary text-white' : 'bg-muted'}`}>{i < stage ? <CheckCircle2 size={15}/> : i + 1}</span>{title}{i === stage && <span className="ml-auto text-[10px] text-primary">Current</span>}</li>)}</ol>
    <div className="rounded-2xl bg-secondary p-4"><p className="flex items-center gap-2 text-sm font-bold"><UserRound size={18}/>{request.passenger}<span className="ml-auto text-[10px] font-normal">Demo passenger</span></p><div className="mt-4 space-y-3">{[request.pickup, request.destination].map((place, i) => <div key={i} className="flex items-start gap-2"><MapPin size={15} className="mt-1 shrink-0 text-primary"/><div><p className="text-[10px] text-muted-foreground">{i === 0 ? 'Pickup' : 'Drop-off'}</p><p className="text-xs font-semibold">{place}</p></div></div>)}</div></div>
    <div className="my-4 grid grid-cols-2 gap-3"><Button variant="outline" className="h-11 rounded-xl text-xs" onClick={() => setModal('chat')}><MessageCircle size={16} className="mr-2"/>Demo chat</Button><Button variant="outline" className="h-11 rounded-xl text-xs" onClick={() => { setCalling(false); setModal('call'); }}><Phone size={16} className="mr-2"/>Demo call</Button></div>
    <Button className="kayan-action w-full" onClick={() => stage < 3 ? onStage(stage + 1) : onFinish(false)}>{['Simulate arrival at pickup', 'Start simulated trip', 'Simulate drop-off', 'Complete demo trip'][stage]}<ArrowRight size={16} className="ml-2"/></Button>
    <Button variant="ghost" className="mt-2 h-10 w-full rounded-xl text-xs text-muted-foreground" onClick={() => onFinish(true)}>Cancel demo trip · no charge</Button>
    <Dialog open={modal !== null} onOpenChange={open => { if (!open) { setModal(null); setCalling(false); } }}><DialogContent className="max-w-md rounded-3xl p-6"><DialogHeader><DialogTitle>{modal === 'chat' ? 'Passenger chat demo' : 'Passenger call demo'}</DialogTitle><DialogDescription>No messages are delivered and no phone call is placed. Replies and connection states are scripted.</DialogDescription></DialogHeader>
      {modal === 'chat' ? <><div role="log" aria-label="Demo conversation" aria-live="polite" className="max-h-64 space-y-3 overflow-y-auto rounded-2xl bg-background p-4">{messages.map((message, i) => <div key={i} className={`max-w-[90%] rounded-2xl p-3 ${message.author === 'You' ? 'ml-auto bg-secondary' : 'border bg-card'}`}><p className="mb-1 text-[10px] font-bold text-primary">{message.author}</p><p className="break-words text-xs leading-5">{message.text}</p></div>)}</div><form className="flex gap-2" onSubmit={e => { e.preventDefault(); if (!draft.trim()) return; setMessages(m => [...m, { author: 'You', text: draft.trim() }, { author: 'Passenger · scripted', text: 'Thanks! See you at the pickup point. (Simulated reply)' }]); setDraft(''); }}><Input aria-label="Demo message" value={draft} maxLength={500} onChange={e => setDraft(e.target.value)} placeholder="Write a demo message…" className="h-12 rounded-xl"/><Button disabled={!draft.trim()} type="submit" className="kayan-action px-4" aria-label="Send demo message"><Send size={18}/></Button></form></> : <div className="py-4 text-center"><span className="mx-auto flex h-20 w-20 items-center justify-center rounded-full bg-secondary text-primary"><Phone size={32}/></span><p className="mt-5 text-lg font-bold">{request.passenger}</p><p role="status" className="mb-6 mt-2 text-sm text-muted-foreground">{calling ? 'Simulated connection · no audio or phone access' : 'Ready to preview a call'}</p><Button className="kayan-action w-full" onClick={() => { if (calling) { setCalling(false); setModal(null); } else setCalling(true); }}>{calling ? 'End simulated call' : 'Simulate connection'}</Button></div>}
    </DialogContent></Dialog>
  </section>;
}
